SecurityError: Failed to execute 'isSessionSupported' on 'XRSystem' when in iframe (#734)
* fix: SecurityError: Failed to execute 'isSessionSupported' on 'XRSystem' when in iframe

fixes: #722

* Update Frontend/library/src/WebXR/WebXRController.ts

* Update Frontend/library/src/WebXR/WebXRController.ts

---------

Co-authored-by: Luke Bermingham <1215582+lukehb@users.noreply.github.com>
(cherry picked from commit cc8c923702af288e8a74265978831acfee52627f)